### ISSUE TITLE
Enabling a tweak based on a specific 'Tag' assigned to course does not seem to work

### ISSUE THREAD

**Issue by markuskiller** [marcusgreen/moodle-tool_tweak#2]
Hi Marcus

When trying to enable a tweak only in courses which are assigned a specific tag, I do not seem to see any difference between courses with the specific tag and courses without that tag.

![image](https://github.com/marcusgreen/moodle-tool_tweak/assets/5632357/75b06564-5699-479e-a554-3cf369ad90c1)

Did I misunderstand this feature or is this something that should work in the proposed way?

The 'simple question edit' tweak seems to be active in both of my test courses but only one has the Tag 'test-tweak-tool' assigned to it.

Have a great day!
Markus

**Comment by marcusgreen** [comment]
The tag feature was designed for teachers to add to a quiz and the contents of the tweak would be added to the selected page within it. I have not thought about how it might be used or applied to a course.

**Comment by markuskiller** [comment]
Alright, I see. In this case, I think the tag_help string needs to be clarified:

![image](https://github.com/marcusgreen/moodle-tool_tweak/assets/5632357/4e6e3dab-f41f-4b3e-87dd-24fdd787cb4b)

![image](https://github.com/marcusgreen/moodle-tool_tweak/assets/5632357/b2fc64c8-b8c2-4198-826b-4bc73e7a137f)

... and the corresponding translation.

**Comment by markuskiller** [comment]
My bad, I found the relevant definition now:

https://docs.moodle.org/dev/Course_module & the examples on the Wiki page are clear enough. 

This was just me being unfamiliar with the terminology.
